module.exports = {
    homePath: "/",
    phonesPath: "/phone",
    watchesPath: "/watch",
    tvsPath: '/tv',
    itemsPath: 'http://localhost:3000/items/type',
    searchPath: '/search',
    productPath: '/product',
    phoneRequest: '/phone',
    tvRequest: '/tv',
    watchRequest: '/watch',
    anyPath: "*",
    searchQueryPath: '/search',
    productByIdRequest:"/items/id/",
    addNewPath: "/add",
    loginPath: "/login",
    signUpPath: "/signup",
    addRequest: "http://localhost:3000/items",
    deleteRequest: "http://localhost:3000/items",
    loginRequest: "http://localhost:3000/users/login",
    signUpRequest: "http://localhost:3000/users/",
    userListPath: '/userlist',
    userListRequest: "http://localhost:3000/users/",
    profilePath: '/profile',
    changePasswordRequest: 'http://localhost:3000/users/'
};